[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
extra_scripts = post:tools/package_release.py

monitor_speed = 115200

lib_deps =
    m5stack/M5Cardputer
    bblanchon/ArduinoJson
    mikalhart/TinyGPSPlus @ ^1.1.0
    earlephilhower/ESP8266Audio @ 2.0.0

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
