"""Build the world's outline layer: borders, coasts and cities only."""
import concurrent.futures
import io
import json
import math
from pathlib import Path
import unicodedata
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/"
URLS = [BASE + "ne_10m_admin_0_boundary_lines_land.geojson",
        BASE + "ne_50m_coastline.geojson",
        "https://download.geonames.org/export/dump/cities15000.zip"]


def fetch(url):
    return urllib.request.urlopen(url, timeout=90).read()


def simplify(points):
    if len(points) <= 2: return points
    ax, ay = points[0][:2]; bx, by = points[-1][:2]
    dx, dy = bx - ax, by - ay; norm = dx * dx + dy * dy
    best, index = 0, 0
    for i, (x, y, *_) in enumerate(points[1:-1], 1):
        t = max(0, min(1, ((x - ax) * dx + (y - ay) * dy) / norm)) if norm else 0
        distance = math.hypot(x - ax - t * dx, y - ay - t * dy)
        if distance > best: best, index = distance, i
    if best <= 0.015: return [points[0], points[-1]]
    return simplify(points[:index + 1])[:-1] + simplify(points[index:])


def cell_for(lon, lat):
    return max(0, min(17, math.floor((lat + 90) / 10))) * 36 + max(0, min(35, math.floor((lon + 180) / 10)))


def split(a, b):
    ax, ay = a[:2]; bx, by = b[:2]
    if abs(bx - ax) > 180:
        bx += 360 if bx < ax else -360
        edge = 180 if bx > ax else -180
        y = ay + (edge - ax) / (bx - ax) * (by - ay)
        yield from split((ax, ay), (edge, y))
        yield from split((-edge, y), (bx - (360 if edge > 0 else -360), by))
        return
    cuts = [0, 1]
    for start, end in [(ax, bx), (ay, by)]:
        if start == end: continue
        for grid in range(math.floor(min(start, end) / 10) + 1, math.ceil(max(start, end) / 10)):
            t = (grid * 10 - start) / (end - start)
            if 0 < t < 1: cuts.append(t)
    cuts = sorted(set(cuts))
    for start, end in zip(cuts, cuts[1:]):
        x1, y1 = ax + start * (bx - ax), ay + start * (by - ay)
        x2, y2 = ax + end * (bx - ax), ay + end * (by - ay)
        cell = cell_for((x1 + x2) / 2, (y1 + y2) / 2)
        west, south = cell % 36 * 10 - 180, cell // 36 * 10 - 90
        values = tuple(round(v * 1000) for v in (x1 - west, y1 - south, x2 - west, y2 - south))
        assert all(0 <= v <= 10000 for v in values)
        if values[:2] != values[2:]: yield cell, values


def main():
    with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
        borders, coasts, cities = list(pool.map(fetch, URLS))
    segments = [[] for _ in range(648)]; towns = [[] for _ in range(648)]
    for data in (borders, coasts):
        for f in json.loads(data)['features']:
            g = f['geometry']
            paths = [g['coordinates']] if g['type'] == 'LineString' else g['coordinates']
            for path in paths:
                points = simplify(path)
                for a, b in zip(points, points[1:]):
                    for cell, segment in split(a, b): segments[cell].append(segment)
    with zipfile.ZipFile(io.BytesIO(cities)) as z:
        for row in z.read('cities15000.txt').decode().splitlines():
            f = row.split('\t'); lat, lon, pop = float(f[4]), float(f[5]), int(f[14])
            cell = cell_for(lon, lat); west, south = cell % 36 * 10 - 180, cell // 36 * 10 - 90
            name = unicodedata.normalize('NFKD', f[2]).encode('ascii', 'ignore').decode()
            towns[cell].append((pop, name, round((lat - south) * 1000), round((lon - west) * 1000)))
    lines = ['// Generated by tools/generate_outline.py; Natural Earth/GeoNames. See MAP_SOURCES.md.',
             '#pragma once', '#include <stdint.h>',
             'struct OutlineSegment { uint16_t lon1, lat1, lon2, lat2; };',
             'struct OutlineTown { const char* name; uint16_t lat, lon; };',
             'struct OutlineCell { uint32_t segmentStart, townStart; uint16_t segmentCount, townCount; };',
             'static const OutlineSegment OUTLINE_SEGMENTS[] = {']
    for cell in segments: lines += ['    {' + ', '.join(map(str, s)) + '},' for s in cell]
    lines += ['};', 'static const OutlineTown OUTLINE_TOWNS[] = {']
    for cell in towns:
        cell.sort(reverse=True)
        lines += [f'    {{{json.dumps(name)}, {lat}, {lon}}},' for _, name, lat, lon in cell]
    lines += ['};', 'static const OutlineCell OUTLINE_CELLS[648] = {']
    a = b = 0
    for segments_in_cell, towns_in_cell in zip(segments, towns):
        lines.append(f'    {{{a}, {b}, {len(segments_in_cell)}, {len(towns_in_cell)}}},')
        a += len(segments_in_cell); b += len(towns_in_cell)
    lines += ['};', '']
    (ROOT / 'include' / 'outline_data.h').write_text('\n'.join(lines), encoding='utf-8')
    print(f'Outline: {a} segments, {b} cities worldwide.')


if __name__ == '__main__': main()
